FROM oven/bun:1.3.1-alpine

ARG APP_PORT

ARG APP_HOST

ARG NITRO_PORT

ENV APP_PORT=$APP_PORT

ENV APP_HOST=$APP_HOST

ENV NITRO_PORT=$NITRO_PORT

ENV SHELL=bash

WORKDIR /app

COPY package*.json ./

RUN bun install

COPY . ./

RUN bun run build

EXPOSE $NITRO_PORT

CMD ["bun", "run", "start"]
