FROM node:25.1.0-alpine3.22

ARG APP_PORT

ARG APP_HOST

ARG NITRO_PORT

ENV APP_PORT=$APP_PORT

ENV APP_HOST=$APP_HOST

ENV NITRO_PORT=$NITRO_PORT

WORKDIR /app

COPY package*.json ./

RUN npm install -g patch-package && npm install

COPY . ./

RUN npm run build

EXPOSE $NITRO_PORT

CMD ["npm", "run", "start"]
